name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run:  docker build --tag localbuild/steelscript.slim:latest -f Dockerfile.slim .
   
    - name: Scan image
      uses: anchore/scan-action@v3
      with:
        image: "localbuild/steelscript.slim:latest"        

    - name: Run other tests
      run: docker run steelscript.slim
              
